#!/bin/sh /etc/rc.common

START=99

start() {
	if [ ! -e /var/lib/bitmeter/bitmeter.db ]; then
		mkdir -p /var/lib/bitmeter
		cp /usr/lib/bitmeter/bitmeter.db /var/lib/bitmeter
		bmdb webremoteadmin
		bmdb setconfig web.dir "/usr/lib/bitmeter/web/"
	fi
	mkdir -p /var/log/bitmeter/
	touch /var/log/bitmeter/bitmeter.log

	bmcapture &
	bmws &
}

stop() {
	bmdb webstop
	killall bmws
	bmdb capstop
	killall bmcapture
}
