#!/bin/sh /etc/rc.common

START=81

USE_PROCD=1
PROG=/usr/bin/ugps-helper

start_service() {
	local disabled="$(uci get gps.@gps[0].disabled || echo 0)"
	[ "$disabled" = "0" ] || return

	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}
