#!/bin/sh
if [ "x$1" = "xinfo" ]; then
	echo "GPS"
else
	T=$(ubus call gps info)
	AGE=$(echo "$T" | jsonfilter -q -e '@.age')
	[ -z "$AGE" ] && AGE=9999
	[ "$AGE" -le 5 ] && echo "$T" | jsonfilter -e '@.latitude' -e '@.longitude'
fi
exit 0
