#!/bin/sh
if [ "x$1" = "xinfo" ]; then
	echo "Downloaded data on WAN"
else
	IFNAME=$(ifstatus wan | jsonfilter -q -e '@.l3_device')
	[ -z "$IFNAME" ] && exit 0
	cat /sys/class/net/$IFNAME/statistics/rx_bytes
fi
exit 0
