#!/bin/sh

uci set gargoyle.display.status_3ginfo_extended="Cellular Modem"
uci set gargoyle.scripts.status_3ginfo_extended='3ginfo_extended.sh'
uci set gargoyle.status.3ginfo_extended='900'

touch /etc/config/3ginfo
uci -q get 3ginfo.@3ginfo[0] > /dev/null || uci add 3ginfo 3ginfo

uci commit
