#!/bin/sh

uci set gargoyle.display.status_3ginfo_extended="Cellular Modem"
uci set gargoyle.scripts.status_3ginfo_extended='3ginfo_extended.sh'
uci set gargoyle.status.3ginfo_extended='900'
uci commit
