#!/bin/sh

case $ACTION in
	add)
		grep -q /dev/$DEVICENAME /proc/mounts || exit 0
		DIR=$(awk '/^\/dev\/'$DEVICENAME'/ {print $2}' /proc/mounts)
		killall aria2c > /dev/null 2>&1
		aria2.sh "$DIR"
		logger "Aria2 zostala uruchomiona z katalogiem $DIR"
		;;
	remove)
		killall aria2c > /dev/null 2>&1
		;;
esac
