#!/bin/sh

[ "$ACTION" = stratum ] || exit 0

T=""
[ -e /etc/crontabs/root ] && T=$(grep easyconfig_nightmode /etc/crontabs/root)
if [ -n "$T" ]; then
	[ -z "$(pidof sunwait)" ] && /usr/bin/easyconfig_nightmode.sh
fi

exit 0
