#!/bin/sh

[ "$ACTION" = stratum ] || exit 0

[ -e /etc/crontabs/root ] || exit 0

TIMESYNCED="/var/state/easyconfig_timesynced"
[ -e "$TIMESYNCED" ] && exit 0

touch $TIMESYNCED

if grep -q easyconfig_nightmode /etc/crontabs/root; then
	[ -z "$(pidof sunwait)" ] && /usr/bin/easyconfig_nightmode.sh
fi
if grep -q wifi /etc/crontabs/root; then
	/usr/bin/easyconfig_cron_helper.sh startup wifi
fi

exit 0
