#!/bin/sh

[ "$ACTION" = stratum ] || exit 0

TIMESYNCED="/var/state/timesynced"
if [ ! -e "$TIMESYNCED" ]; then
	touch /var/state/timesynced

	T=""
	[ -e /etc/crontabs/root ] && T=$(grep easyconfig_nightmode /etc/crontabs/root)
	if [ -n "$T" ]; then
		[ -z "$(pidof sunwait)" ] && /usr/bin/easyconfig_nightmode.sh
	fi

	/usr/bin/easyconfig_cron_helper.sh startup wifi
fi

exit 0
