#!/bin/sh
T=""
F=/sys/class/hwmon/hwmon*
for f in $F; do
	[ -e $f ] || continue
	[ -e $f/name ] && NAME=$(cat $f/name)
	if [ -n "$NAME" ]; then
		case "$NAME" in
			k10temp|coretemp|armada_thermal)
				for i in $f/temp*_input; do
					[ -n "$T" ] && T="$T, "
					T="$T"$(awk '{if ($1 == 0){printf ""}else{printf "%.2f C", $1/1000}}' $i 2>/dev/null)
				done
				;;
		esac
	fi
done
[ -n "$T" ] && echo "CPU temp: $T"
exit 0
