#!/bin/sh
T=""
F=/sys/class/hwmon/hwmon*
for f in $F; do
	[ -e $f ] || continue
	[ -e $f/name ] && NAME=$(cat $f/name)
	if [ -n "$NAME" ]; then
		case "$NAME" in
			ath10k_hwmon | \
			ath11k_hwmon)
				T1=$(awk '{if ($1 == 0){printf ""}else{printf "%.2f C", $1/1000}}' $f/temp1_input 2>/dev/null)
				if [ -n "$T1" ]; then
					[ -n "$T" ] && T="$T, "
					T="${T}${T1}"
				fi
				;;
		esac
	fi
done
[ -n "$T" ] && echo "Wi-Fi chip temp: $T"
exit 0
