#!/bin/sh /etc/rc.common

START=90
STOP=90

start() {
	[ -e /etc/config/adblock ] && exit 0

	B=/etc/adblock/adblock.blacklist
	W=/etc/adblock/adblock.whitelist

	[ -e /etc/adblock/adblock.blacklist ] || exit 0
	[ -s /etc/adblock/adblock.blacklist ] || exit 0
	[ -e /etc/adblock/adblock.whitelist ] || (mkdir -p "$(dirname "$W")"; touch "$W")

	C=$(uci -q get dhcp.@dnsmasq[0].confdir)
	if [ -z "$C" ]; then
		C="/tmp/dnsmasq.d"
		uci set dhcp.@dnsmasq[0].confdir="$C"
		uci commit dhcp
	fi
	[ -e "$C" ] || mkdir -p "$C"

	grep -x -v -f "$W" "$B" | sed 's|^|address=/|g;s|$|/|g' > "$C/easyconfig.domains"
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

stop() {
	C=$(uci -q get dhcp.@dnsmasq[0].confdir)
	if [ -n "$C" ]; then
		if [ -e "$C/easyconfig.domains" ]; then
			rm "$C/easyconfig.domains"
			/etc/init.d/dnsmasq restart >/dev/null 2>&1
		fi
	fi
}
