#!/bin/sh
T=""
F=/sys/class/hwmon/hwmon*
for f in $F; do
	[ -e $f ] || continue
	[ -e $f/name ] && NAME=$(cat $f/name)
	if [ -n "$NAME" ]; then
		case "$NAME" in
			fam15h_power)
				[ -n "$T" ] && T="$T, "
				T="$T"$(awk '{if ($1 == 0){printf ""}else{printf "%.2f W", $1/1000000}}' $f/power1_average 2>/dev/null)
				;;
		esac
	fi
done
[ -n "$T" ] && echo "CPU power: $T"
exit 0
