#!/bin/sh

uci set gargoyle.display.system_atcmd='AT Commands'
uci set gargoyle.scripts.system_atcmd='atcmd.sh'
uci set gargoyle.system.atcmd='351'

touch /etc/config/3ginfo
uci -q get 3ginfo.@3ginfo[0] > /dev/null || uci add 3ginfo 3ginfo

uci commit
