#!/bin/sh
F=/sys/bus/cpu/devices/cpu*/cpufreq
for f in $F; do
	[ -e $f ] || continue
	if [ -e $f/scaling_cur_freq ]; then
		[ -n "$T" ] && T="$T, "
		T="$T"$(awk '{if ($1 >= 1000000) {printf "%.2fGHz", $1/1000000} else {printf "%.2fMHz", $1/1000}}' $f/scaling_cur_freq)
	else
		if [ -e $f/cpuinfo_cur_freq ]; then
			[ -n "$T" ] && T="$T, "
			T="$T"$(awk '{if ($1 >= 1000000) {printf "%.2fGHz", $1/1000000} else {printf "%.2fMHz", $1/1000}}' $f/cpuinfo_cur_freq)
		fi
	fi
done
[ -n "$T" ] && echo "CPU freq: $T"
