#!/bin/sh

[ $ACTION = "ifup" ] || exit 0

if [ $INTERFACE = "wan" ]; then
	awk '{printf "%d\n", $1}' /proc/uptime >> /tmp/easyconfig_wan_up

	VPNS=$(uci show network | awk -F. '/trigger='\''wan'\''$/{print $2}')
	if [ -n "$VPNS" ]; then
		sleep 5
		for VPN in $VPNS; do
			if [ "x$(uci -q get network.$VPN.auto)" = "x0" ]; then
				ifup $VPN
			fi
		done
	fi

	OVPNS=$(uci show openvpn | awk -F. '/trigger='\''wan'\''$/{print $2}')
	if [ -n "$OVPNS" ]; then
		sleep 5
		for OVPN in $OVPNS; do
			uci set openvpn.$OVPN.enabled=1
		done
		/etc/init.d/openvpn restart
		uci revert openvpn
	fi
fi

exit 0
